#!/usr/bin/env python
import sys, os

def options(opt):
    opt.load('g++')
    opt.load('boost')
    opt.load('gtest')
    opt.recurse('..')

def configure(cfg):
    cfg.load('g++')
    cfg.load('boost')
    cfg.load('gtest')

    cfg.check_boost(
            lib='serialization system thread filesystem',
            uselib_store='BOOST')

    cfg.check_cxx(
            lib='mongoclient',
            uselib_store='MONGOLIB')

    cfg.recurse('..')

def build(bld):
    bld.recurse('..')

    flags = {
        "cxxflags" : [
            '-std=c++0x',
            '-g',
            '-O0',
            '-pedantic',
            '-Wall',
            '-Wextra',
            ],
    }

    from gtest import summary
    bld(
        target       = 'test-main',
        features     = 'gtest cxx cxxprogram',
        source       = bld.path.ant_glob('*.cc'),
        use          = ['boost_patches', 'BOOST', 'MONGOLIB'],
        install_path = os.path.join('bin', 'test'),
        **flags
    )
    bld.add_post_fun(summary)
