#!/usr/bin/env python

import os

try:
    from waflib.extras import symwaf2ic
    from waflib.extras.gtest import summary
    recurse = lambda *args, **kwargs: None
    old_waf = False
except ImportError:
    from gtest import summary
    from symwaf2ic import recurse_depends
    recurse = lambda ctx: recurse_depends(depends, ctx)
    old_waf = True


def options(opt):
    opt.load('compiler_cxx')
    opt.load('boost')
    opt.load('gtest')
    opt.recurse('..')


def configure(cfg):
    cfg.load('compiler_cxx')
    cfg.load('boost')
    cfg.load('gtest')

    cfg.check_boost(
        lib='serialization system thread filesystem',
        uselib_store='BOOST')

    cfg.recurse('..')


def depends(ctx):
    pass

def build(bld):
    bld.recurse('..')

    flags = {
        "cxxflags": [
            '-std=c++0x',
            '-g',
            '-O0',
            '-pedantic',
            '-Wall',
            '-Wextra',
        ],
    }

    from waflib.extras.gtest import summary
    bld(
        target='test-serialization',
        features='gtest cxx cxxprogram',
        source=bld.path.ant_glob('*.cc'),
        use=['boost_patches', 'BOOST'],
        install_path=os.path.join('bin', 'test'),
        includes='.',
        **flags
    )
    bld.add_post_fun(summary)
